name: btc-trading-bot

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8000:8000"